CHANGELOG.md
README.md

chore: Add initial README and CHANGELOG

---

Cargo.toml
src/client.rs
src/server.rs
tests/tests.rs

tests: Add an initial self-test

---

proxy/.gitignore
proxy/src/config.rs
proxy/src/main.rs

feat(proxy): Print a list of services on startup

---

src/client.rs
src/lib.rs
src/receive.rs
src/send.rs
src/server.rs
src/stream.rs

Closes #39, Closes #40
~This should wait until #37 is closed.~
I'll merge this to get some issues closed.

chore: Add `Debug` implementations + deny unsafe code

---

proxy/.gitignore
proxy/Cargo.toml
proxy/config.toml
proxy/src/main.rs

Requesting a review due to the additional dependency. Maybe you have another preference. But `argh`seems to be a very small dependency (and I like the concept).

feat(proxy): Implement minimal argument processing

---

Cargo.toml
tag-generator/Cargo.toml
tag-generator/src/lib.rs

feat: Add `TagGenerator`

---

proxy/README.md

docs(proxy): Add `README.md`

---

CHANGELOG.md
README.md
proxy/README.md

This PR adds a bit of context for someone reviewing this repository closing #63. Furthermore, it closes #62, and #65.
I'm requesting a review because this PR changes the most visible project information and I don't want to do this without consensus.
We can merge it after #60.

docs: Make work on milestones more visible

---

Cargo.toml
proxy/src/proxy.rs
proxy/src/util.rs
src/client.rs
src/send.rs
tasks/src/lib.rs

Only chore to make the review of #71 easier. I don't think there is much to review here. I'll go ahead and merge. Hope that's okay :-)

chore: Use `imap-{types,codec}` `v2`

---

examples/client.rs
proxy/src/proxy.rs
proxy/src/util.rs
src/client.rs
src/send.rs
src/server.rs
tasks/src/lib.rs

Closes #75, #77 
I already refactored a bit. We can drop irrelevant commits here but I think the refactoring should be fine.

feat: Forward command continuation response requests

---

src/client.rs
src/server.rs

We stumbled across this topic some time ago. With this PR I add comments that explain why I originally decided to implement "send before receive" in `ClientFlow` and `ServerFlow`. I duplicated the comment because IMO it's more important to have this comment in the right place than to reduce duplication.

docs: Explain why we send before we receive

---

Cargo.toml
examples/client.rs
examples/client_authenticate.rs
examples/server.rs
examples/server_authenticate.rs
proxy/src/proxy.rs
proxy/src/util.rs
src/client.rs
src/lib.rs
src/receive.rs
src/send.rs
src/server.rs
src/types.rs
tasks/examples/client.rs
tasks/src/lib.rs
tasks/src/tasks.rs
tests/tests.rs

Closes #71 
I already merged all minor changes, typos, reformatting, etc. on main. This branch is a cleaned-up (and rebased) version of `git diff duesee_issues_16_v2`.
Multiple things happen here (see commits):
* TaskMap (could be a separate PR)
* AUTHENTICATE for imap-flow
* Please look at the fix in particular. I think we accidentally introduced a bug during the "Dummy refactoring".
* AUTHENTICATE for proxy (could be a separate PR)
* AUTHENTICATE for tasks (could be a separate PR)

feat: Implement AUTHENTICATE flow

---

Cargo.toml
examples/client_idle.rs
examples/server_idle.rs
proxy/src/proxy.rs
proxy/src/util.rs
src/client.rs
src/send.rs
src/server.rs
tasks/src/lib.rs

feat: Idle

---

examples/client.rs
examples/client_authenticate.rs
examples/client_idle.rs
examples/server.rs
examples/server_authenticate.rs
examples/server_idle.rs
proxy/Cargo.toml
proxy/src/proxy.rs
proxy/src/util.rs
src/client.rs
src/send.rs
src/server.rs
src/types.rs
tasks/Cargo.toml
tasks/examples/client.rs
tasks/src/lib.rs
tasks/src/tasks.rs
tests/tests.rs

chore: Minor issues

---

proxy/README.md

docs: Describe supported authentication mechanisms

---

src/server.rs

bug: Use BAD when rejecting literals

---

tag-generator/src/lib.rs

test(tag-generator): Fix `test_generator_generator`

---

flow-test/src/client_tester.rs
flow-test/src/server_tester.rs
flow-test/tests/flow-test-client.rs
flow-test/tests/flow-test-server.rs
src/client.rs
src/server.rs

Closes #116.
Adds some tests for  #118.

Change default for crlf_relaxed to false

---

proxy/src/proxy.rs

feat(proxy): Log handles (+ logging improvements)

---

examples/client_authenticate.rs
proxy/src/proxy.rs
src/client.rs
src/tests.rs
tasks/src/lib.rs

refactor!: Merge `ClientFlowEvent::{AuthenticateAccepted,AuthenticateRejected}`

---

.github/workflows/build_and_test.yml
src/stream.rs

ci: Deny warnings in debug and release

---

src/handle.rs

fix(imap-flow): Fix `HandleGenerator::generate`

---

src/handle.rs

Follow-up PR for #150. Also see #149.

test: Add test for `HandleGenerator`

---

tasks/src/tasks/logout.rs
tasks/src/tasks/mod.rs
tasks/src/tasks/starttls.rs

Also adjusted the `LogoutTask` to match style of other tasks.

Add `StartTlsTask`

---

tasks/src/tasks/append.rs
tasks/src/tasks/appenduid.rs
tasks/src/tasks/capability.rs
tasks/src/tasks/check.rs
tasks/src/tasks/mod.rs
tasks/src/tasks/noop.rs

Also adjusted `NoOpTask` and `CapabilityTask` to match style of other tasks.

Add `AppendTask`, `AppendUidTask` and `CheckTask`

---

src/stream.rs

fix: Handle closed TLS session properly

---

integration-test/src/client_tester.rs
integration-test/src/server_tester.rs
integration-test/tests/client.rs
integration-test/tests/server.rs

test: Add tests for closed stream

---

src/stream.rs

bug: Fix greeting timeout with TLS

---

.github/workflows/main.yml
justfile

build: Increase MSRV and split up minimal versions job

---

src/client.rs

Add option to discard greeting
