- .github/workflows/build_and_test.yml
- Cargo.toml
- proxy/Cargo.toml
- proxy/config.toml
- proxy/src/config.rs
- proxy/src/main.rs
- proxy/src/proxy.rs
- proxy/src/util.rs
First prototype for an IMAP proxy.
It can be run with:
```sh
cd proxy
RUST_LOG=proxy=trace cargo run
```
There is a default config file located at `proxy/config.toml`. It contains ports that can be used to connect with a local email client.
The change set contains some TODOs. We need to create issues for them after merging this PR.
Closes #13
> proxy: Implement prototype

- examples/client.rs
- examples/server.rs
I initially wanted to copy the examples from `imap` and `async_imap`. However, in order to do so, we already need a higher-level API. It doesn't make a lot of sense to implement these examples now. So, for now, I'll use the examples as playground for just the things we want to abstract over in imap-flow, i.e., literal handling, authentication, and idle, and be careful to not do too much already.
> docs: Provide simple client and server examples

- examples/client.rs
- proxy/src/proxy.rs
- src/client.rs
- src/send.rs
- src/server.rs
Before this PR:
- If `ClientFlow` receives a `Status::Bad` with the matching tag then the current `Command` will be aborted
- All received `Status` (including the one mentioned before) will be emitted via `ClientFlowEvent::StatusReceived`
- `ClientFlowEvent::StatusReceived` does not contain the `ClientFlowCommandHandle`
- The user of `ClientFlow` must do complicated logic in order to detect the abortion of the `Command`
After this PR:
- If `ClientFlow` receives a `Status::Bad` with the matching tag then the current `Command` will be aborted and `ClientFlowEvent::CommandRejected` will be emitted
-  `ClientFlowEvent::CommandRejected` contains the `ClientFlowCommandHandle`
- All other received `Status` will be emitted via `ClientFlowEvent::StatusReceived`
Why this might be a good idea:
- …
> feat: Improve handle handling

- proxy/src/proxy.rs
> chore(proxy): Use `error` instead of `info` on discard or io error

- Cargo.toml
- deny.toml
- tasks/Cargo.toml
- tasks/examples/client.rs
- tasks/src/lib.rs
- tasks/src/tasks.rs
This is the current state of the `tasks` crate. I already like how working with it feels, but I am relatively sure we will want to change a few things as we go.
The next thing I would like to do is to port the "CLI demo" -- the thing that fetches all status data items from a server -- from the `duesee_cli` branch to `tasks` and fix everything on the way.
There are some open questions regarding error handling (that we probably should discuss in person), an `unwrap`, and a few missed opportunities for better code.
I feel that we can still be more liberal with anything that is not `imap-flow` for now. Thus, I'm primarily making this PR to have something usable online. What do you think?
By the way, I kept all commits in case they're helpful, but we probably should squash to a single commit …
> feat: First draft of `tasks`

- proxy/src/proxy.rs
- src/client.rs
- src/receive.rs
- src/send.rs
- src/server.rs
- src/stream.rs
Detect a closed stream when writing to or reading from the stream and emit an error.
I decided to add another error variant instead of event variant. It felt more natural and the implementation looks nice.
I also decided to add more stuff to the `stream` module because it helped to reduce code duplication.
With this PR I consistently get the following proxy log messages after closing the client:
```text
ERROR service{name="GMX"}:client{addr=127.0.0.1:36884}: Connection terminated role="s2p" error=Stream was closed
ERROR service{name="GMX"}:client{addr=127.0.0.1:36894}: Connection terminated role="s2p" error=Stream was closed
ERROR service{name="Zoho Mail"}:client{addr=127.0.0.1:54410}: Connection terminated role="c2p" error=Stream was closed
ERROR service{name="Zoho …
```
> feat: Handle closed stream

- Cargo.toml
- src/stream.rs
> feat: Introduce `io/{read,write}/raw` trace events in imap-flow

- src/send_response.rs
- src/server.rs
I hope this makes the module `send_response` more readable. If you like it I'll continue with `send_command`.
> chore: Refactor `send_response`

- src/receive.rs
- src/server.rs
Simplify our `NoCodec` hack by removing the trait bound from `ReceiveState`.
> chore: Simplify `NoCodec`

- proxy/src/util.rs
- tasks/src/tasks.rs
Fixes a breaking change in `imap-types`. The type `NonEmptyVec` was replaced with `Vec1`.
> chore: Migrate to newer `imap-types`

- proxy/src/proxy.rs
- src/client.rs
- src/server.rs
We have two option types: `ServerFlowOptions` and `ClientFlowOptions`. We might want to add additional fields to them in the future. It would be nice if we were able to do that without a breaking change. So I propose:
- Let's make them `#[non_exhaustive]`. This allows us to add fields.
- Let's make `ClientFlowOptions` non-`Copy`. This allos us to add non-`Copy` fields.
The `Codec` types in `imap-codec` already do this.
Caveat: To my surprise the `..` notation does not work with `#[non_exhaustive]` (maybe in the future, see https://github.com/rust-lang/rust/issues/70564#issuecomment-1409770088). So this doesn't work:
```rust
let options = ServerFlowOptions {
crlf_relaxed: false,
..ServerFlowOptions::default()
}
```
Instead you need to write this:
```rust
let mut options = …
```
> refactor: Make option types more backwards compatible

- examples/client_authenticate.rs
- examples/client_idle.rs
- proxy/src/proxy.rs
- proxy/src/util.rs
- src/client.rs
- src/receive.rs
- src/send_command.rs
- src/send_response.rs
- src/server.rs
- src/types.rs
The module `send_command` contains probably the most complicated code in this repository. I tried to refactor it and I think it's better now, though not perfect.
Highlights:
- Regular commands, authenticate and idle are handled completely separately without much code duplication
- Better state machines
- `SendCommandState::progress` is short and readable
- I was able to move `ClientFlow::maybe_finish_command` to the `send_command` module and it looks much simpler now.
I tested it by using our proxy and it seems to work.
> refactor: Rewrite module `send_response`

- Cargo.toml
- flow-test/Cargo.toml
- flow-test/README.md
- flow-test/src/client_tester.rs
- flow-test/src/codecs.rs
- flow-test/src/lib.rs
- flow-test/src/mock.rs
- flow-test/src/runtime.rs
- flow-test/src/server_tester.rs
- flow-test/src/test_setup.rs
- flow-test/tests/both.rs
- flow-test/tests/client.rs
- flow-test/tests/server.rs
First attempt to introduce a test setup that allows to write tests conveniently.
My design constraints:
- Test should have as few boilerplate as possible
- We want to write **many** tests
- `ClientFlow` and `ServerFlow` are tested separately
- It's possible that both of them could have the same bug that can't be observed if tested simultaneously
- There should be test setups for both of them
- Each test setup is mocking the other side with very simple code
- A test should not spawn any additional threads
- This makes debugging easier
- It should be possible to run multiple tests in parallel
- This is the default for `cargo test`
- Ports might be a problem
- Tokio runtime might be a problem
> test: Introduce crate `flow-test`

- flow-test/src/client_tester.rs
- flow-test/src/runtime.rs
- flow-test/src/server_tester.rs
- flow-test/tests/both.rs
- flow-test/tests/client.rs
- flow-test/tests/server.rs
I added some tests for literal handling
- Login with literals
- Login with rejected literal
- Login with literals and unexpected status that does not reject the literal
I needed to to do some minor changes to `flow-test`. It's nice how flexible `flow-test` is for writing the test flows. I really like it!
> test: Add literal tests

- src/receive.rs
Reduce the complexity of line parsing from O(n²) to O(n).
Tested with:
```
cargo +nightly test --package flow-test --test flow-test-client noop_with_large_lines -- -Z unstable-options --report-time
```
Sample 1
```rust
const LARGE: usize = 10 * 1024 * 1024;
```
```
test noop_with_large_lines ... ok <0.862s>
```
Sample 2
```rust
const LARGE: usize = 100 * 1024 * 1024;
```
```
test noop_with_large_lines ... ok <8.781s>
```
Sample 3
```rust
const LARGE: usize = 1000 * 1024 * 1024;
```
```
test noop_with_large_lines ... ok <90.486s>
```
Closes #128.
> refactor: Optimize line parsing

- examples/client.rs
- examples/client_authenticate.rs
- examples/client_idle.rs
- proxy/src/proxy.rs
- src/client.rs
- src/server.rs
- tasks/src/lib.rs
- tasks/src/tasks.rs
I'm still not happy about our names but now the semantics are right.
> refactor!: fix wrong usage of the term `continuation`

- flow-test/src/server_tester.rs
- flow-test/tests/flow-test-server.rs
- proxy/src/proxy.rs
- src/client.rs
- src/receive.rs
- src/send_command.rs
- src/send_response.rs
- src/server.rs
- src/stream.rs
> feat: Implement read limit

- Cargo.toml
- deny.toml
- examples/client.rs
- examples/client_authenticate.rs
- examples/client_idle.rs
- examples/client_std.rs
- examples/server.rs
- examples/server_authenticate.rs
- examples/server_idle.rs
- flow-test/src/client_tester.rs
- flow-test/src/runtime.rs
- flow-test/src/server_tester.rs
- flow-test/tests/flow-test-server.rs
- proxy/src/proxy.rs
- src/client.rs
- src/lib.rs
- src/receive.rs
- src/send_command.rs
- src/send_response.rs
- src/server.rs
- src/stream.rs
- src/tests.rs
- tasks/examples/client-tasks.rs
- tasks/src/lib.rs
These types are now sans I/O:
- `imap_flow::client::ClientFlow`
- `imap_flow::server::ServerFlow`
- `imap_tasks::Scheduler`
All of them implement the new trait `imap_flow::Flow` which provides just enough interface for implementing I/O utilities. 
For interacting with I/O there is now the optional utility `imap_flow::stream::Stream` based on `tokio` and `tokio_rustls`. This utility and its dependencies can be enabled/disabled with the feature flag `stream` which is enabled by default.
The current usage looks like this:
```rust
let stream = TcpStream::connect("127.0.0.1:12345").await.unwrap();
let mut stream = Stream::insecure(stream);
let mut client = ClientFlow::new(ClientFlowOptions::default());
let greeting = loop {
match stream.progress(&mut client).await.unwrap() { …
```
> refactor: Implement sans I/O

- .github/workflows/build_and_test.yml
- Cargo.toml
- deny.toml
- proxy/Cargo.toml
- proxy/src/proxy.rs
- proxy/src/util.rs
I bumped `rustls@0.23.1` and `tokio-rustls@0.26.0`.
I also replaced `webpki-roots` by `rustls-native-certs` (see [why](https://github.com/rustls/rustls-native-certs?tab=readme-ov-file#should-i-use-this-or-webpki-roots)), and put native certs loading in a static [`Lazy`](https://crates.io/crates/once_cell) cell.
---
What is the prefered method to test examples (the server `127.0.0.1:12345`)?
> Upgrade `rustls` and `tokio-rustls`

- Cargo.toml
- tasks/Cargo.toml
- tasks/examples/client-resolver.rs
- tasks/examples/client-scheduler.rs
- tasks/examples/client-tasks.rs
- tasks/src/lib.rs
- tasks/src/resolver.rs
Split version of #165, part 1.
- Added core changes
- Added the new `Resolver` flow that aims to enqueue task AND get resolution straight. `Resolver::run_task` returns a new `Flow` called `TaskResolver` that can feed `Stream::progress`.
- Made sure `Scheduler` and `Resolver` are `Send`.
> Task runner (mid-level API), part 1

- src/stream.rs
Mostly needed for STARTTLS, see usage at https://github.com/duesee/imap-flow/pull/174/files#diff-3f7e738903cc8204a4e3b1c8ab4db5812898e6bb5ad8b6c7b36df42e29481a8fR197
> Implement `Stream` to `TcpStream` conversion

- flow-test/tests/flow-test-server.rs
- flow-test/tests/flow-test.rs
- proxy/src/proxy.rs
- src/server.rs
First attempt. We could make it work with `&'static str` and `String`... Closes #170.
> fix!: Check CCR creation early to avoid panic (or late error handling)

- src/server.rs
The current text might imply that the command was somehow automatically rejected, similar to `Error::LiteralTooLong`. But that's not the case. The user is responsible for sending a BAD.
> fix: Change `Display` text of `Event::CommandTooLong`

- Cargo.lock
- Cargo.toml
Without this `cargo update` changes the used revisions which might break the build.
> build: Fix patch revisions

- proxy/src/proxy.rs
- proxy/src/util.rs
This is a subset of #241 that just clean up the implementation of the proxy and fixes some minor logging issues.
> refactor(proxy): General cleanup of implementation and logging

- Cargo.lock
- Cargo.toml
- integration-test/Cargo.toml
This won't work until [I](https://github.com/duesee/imap-codec/pull/567) is merged and `imap-codec 2.0.0-alpha.4` is published. This is how it would look like. I made this PR so that we can discuss.
Closes #257.
> chore: forward features to `imap-codec`
